import Link from "next/link";

export const metadata = {
  title: "Terms of Service — Lshoot",
  description: "Terms of Service for Lshoot, a local-first ASO tool",
};

export default function TermsPage() {
  return (
    <div
      className="min-h-screen"
      style={{ background: "#fafaf9", color: "#1c1917" }}
    >
      <header
        className="sticky top-0 z-10 backdrop-blur border-b"
        style={{
          background: "rgba(250, 250, 249, 0.85)",
          borderColor: "#e7e5e4",
        }}
      >
        <div className="container mx-auto max-w-4xl px-6 py-4 flex items-center justify-between">
          <Link
            href="/"
            className="text-sm hover:underline"
            style={{ color: "#78716c" }}
          >
            ← Home
          </Link>
          <h1 className="font-semibold">Terms of Service</h1>
          <div className="w-[50px]" />
        </div>
      </header>

      <article
        className="container mx-auto max-w-3xl px-6 py-12
        [&_h2]:text-xl [&_h2]:font-bold [&_h2]:mt-10 [&_h2]:mb-3
        [&_p]:my-3 [&_p]:leading-relaxed
        [&_ul]:my-3 [&_ul]:pl-6 [&_ul]:list-disc [&_li]:my-1
        [&_code]:px-1.5 [&_code]:py-0.5 [&_code]:rounded [&_code]:text-sm [&_code]:font-mono [&_code]:bg-[#f5f5f4]
        [&_a]:underline
      "
        style={{ color: "#1c1917" }}
      >
        <p className="text-sm" style={{ color: "#78716c" }}>
          Last updated: April 2026
        </p>

        <h2>1. Acceptance of Terms</h2>
        <p>
          By cloning, installing, running, or modifying Lshoot (the "Software"), you
          agree to these Terms of Service. If you do not agree, do not use the
          Software.
        </p>

        <h2>2. What Lshoot Is</h2>
        <p>
          Lshoot is a local-first code-first ASO screenshot generator. The Software
          runs entirely on your machine. There is no remote server, no account, no
          cloud storage, and no telemetry.
        </p>

        <h2>3. License and Protected Areas</h2>
        <p>You are free to modify, fork, and use every file in this repository for your own projects, with two exceptions:</p>
        <ul>
          <li>
            <strong>The landing page</strong> (<code>app/page.tsx</code>) carries the
            brand identity of the original author (Raymond Dzery Hago) and must not be
            modified without permission. A git pre-commit hook enforces this rule.
          </li>
          <li>
            <strong>The <code>flipia</code> project</strong> (<code>projects/flipia/</code>) is the
            personal work of the original author. Exporting this project requires a
            developer code.
          </li>
        </ul>
        <p>
          Every other file — including <code>@/components/aso</code>, the libraries
          in <code>lib/</code>, the documentation, and any project you create in{" "}
          <code>projects/</code> — is yours to modify freely.
        </p>

        <h2>4. No Warranty</h2>
        <p>
          The Software is provided "as is", without warranty of any kind, express or
          implied. The author makes no representations that the Software will be
          error-free or that all bugs will be fixed.
        </p>

        <h2>5. Limitation of Liability</h2>
        <p>
          In no event shall the author be liable for any claim, damages, or other
          liability arising from the use of the Software — including but not limited
          to: rejected App Store or Play Store submissions, loss of data, or lost
          business opportunities.
        </p>

        <h2>6. Third-Party Dependencies</h2>
        <p>
          Lshoot uses open-source dependencies (Next.js, Puppeteer, Sharp, Tailwind,
          shadcn/ui, and others). Each is governed by its own license, available in
          the <code>node_modules</code> folder after installation.
        </p>

        <h2>7. Export Output</h2>
        <p>
          PNGs generated by the Software belong to you. You are responsible for
          ensuring you have the rights to any assets you upload to your projects
          (app screenshots, brand fonts, etc.) and any copy you write.
        </p>

        <h2>8. Contact</h2>
        <p>
          For questions about these terms, see the{" "}
          <Link href="/contact">contact page</Link>.
        </p>
      </article>

      <Footer />
    </div>
  );
}

function Footer() {
  return (
    <footer
      className="border-t"
      style={{ borderColor: "#e7e5e4", background: "#f5f5f4" }}
    >
      <div
        className="container mx-auto max-w-6xl px-6 py-8 flex flex-wrap items-center justify-between gap-4 text-[13px]"
        style={{ color: "#78716c" }}
      >
        <span>© {new Date().getFullYear()} Raymond Dzery Hago · Lshoot</span>
        <div className="flex items-center gap-5">
          <Link href="/terms" className="hover:text-[#1c1917]">
            Terms
          </Link>
          <Link href="/privacy" className="hover:text-[#1c1917]">
            Privacy
          </Link>
          <Link href="/contact" className="hover:text-[#1c1917]">
            Contact
          </Link>
        </div>
      </div>
    </footer>
  );
}
